### ISSUE TITLE
Relays does not behave as expected from the source code.

### ISSUE THREAD

**Issue by voibit** [SequentMicrosystems/ioplus-rpi#15]
Relays does not behave as expected from inspecting the source code.
writing at i2c offset 0x02  does not reset outputs.
writing  at i2c offset 0x01 does let me control relay 3,4,5,6,7 using bitmask, and not seting specified channel as expected.

i am guessing it is a firmware issue, but would let you know faulty firmware is being shipped.

Here is the mapping i found using i2cset

value | binary | output (relay)
---|-----| ----
8  | 0000 1000 |  6 
16 | 0001 0000 |  4
32 | 0010 0000 |  5
64 | 0100 0000 |  3
128 | 1000 0000 | 7

**Comment by alexburcea2877** [comment]
Hi,
A couple of questions: 
 - Did the command line interface behave normally?
 - What is your hardware version (is printed on the card or better send a picture)?
 - Why are you creating your own driver as long as few are written already? 

Recommendation:
 - Do as the cli does, by read-modify-write. [ ioplus.c](https://github.com/SequentMicrosystems/ioplus-rpi/blob/master/src/ioplus.c) line 405

**Comment by voibit** [comment]
Did the command line interface behave normally?
- No, it segfaults before being able to issue commands. 
- python is not an option

What is your hardware version (is printed on the card or better send a picture)?
-  standby

Why are you creating your own driver as long as few are written already?
- because I am using multiple different cards, and want a single codebase with tight time control

Do as the cli does, by read-modify-write. [ioplus.c](https://github.com/SequentMicrosystems/ioplus-rpi/blob/master/src/ioplus.c) line 405
- I will try, but it does not explain the unexpected behavior that was found. 

I am expecting


value | binary | output (relay)
---|-----| ----
1 |0000 0001| 1
2 |0000 0010| 2
4 | 0000 0100| 3
8  | 0000 1000 |  4 
16 | 0001 0000 |  5
32 | 0010 0000 |  6
64 | 0100 0000 |  7
128 | 1000 0000 | 8

**Comment by alexburcea2877** [comment]
The set and clear registers are not maintained for quite some time and might be wrong. I can check the firmware if you need them but I am not sure why the update software does not work on Arch Linux.
Let me know if the read-modify-write mechanism at address 0x00 works as expected.

**Comment by voibit** [comment]
I do not need the set and clear registers, as long as the 0x00 register is working as expected. Does read trigger anything the firmware? I am only interested setting bits.

**Comment by alexburcea2877** [comment]
No, the read does not trigger anything in the firmware. I was proposed the mechanism in case you need to change the state of a single relay and keep the rest of them unchanged, but if you know the state of all the relays, a write is enough.
Please advise me on how you install the Arch Linux, I intend to test with, thanks.

**Comment by voibit** [comment]
It is a little cumbersome, at least for the pi5

I followed the guide in https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4, for the aarch64 build.
You may additionally need the pi foundation kernel, or install/copy [uboot](https://archlinuxarm.org/packages/aarch64/uboot-raspberrypi) for booting the mainline kernel. 

if you have an arch system (x86_64) running, I suggest chroot into the sdcard after copying files  with `sudo arch-chroot /mnt` then install pi kernel with `sudo pacman -S linux-rpi`

**Comment by voibit** [comment]
I am sorry. It seems like I had mixed up the relay 8 card with this one. The mappings fits with the relay 8 card.
