### ISSUE TITLE
raspbian buster as berryboot image - SMBus problem

### ISSUE THREAD

**Issue by Jusufs** [SequentMicrosystems/ioplus-rpi#4]
Hi,
i have some problem on newest raspbian buster as berryboot image.
After boot example is not working.

Message:
root@rpi4:/home/pi/ioplus-rpi/python/examples# python3 relaytest.py 0
Traceback (most recent call last):
  File "relaytest.py", line 13, in <module>
    io.setRelayCh(stackLevel, i +1, 1)
  File "/usr/local/lib/python3.7/dist-packages/libioplus/__init__.py", line 93, in setRelayCh
    bus = smbus.SMBus(1)
FileNotFoundError: [Errno 2] No such file or directory

After manually enabled I2S example is working. But after reboot same error message.
Thanks for help.
P.S.
On normally installed raspbian this is no problem.

SORRY, please delete this issue !!!
A config.txt line was necessary to add in berryboot menu
dtparam=i2c_arm=on

**Comment by alexburcea2877** [comment]
No problem, it might help someone.
