### ISSUE TITLE
[node-red-contrib-sm-ioplus/ioplus] Error: Cannot find module 'i2c-bus'

### ISSUE THREAD

**Issue by hanyscz** [SequentMicrosystems/ioplus-rpi#6]
`Starting as a systemd service.
11 Jun 15:33:27 - [info]
Welcome to Node-RED
===================
11 Jun 15:33:27 - [info] Node-RED version: v1.3.5
11 Jun 15:33:27 - [info] Node.js  version: v14.16.1
11 Jun 15:33:27 - [info] Linux 5.10.17-v7l+ arm LE
11 Jun 15:33:28 - [info] Loading palette nodes
11 Jun 15:33:29 - [info] Dashboard version 2.29.1 started at /ui
11 Jun 15:33:30 - [warn] ------------------------------------------------------
11 Jun 15:33:30 - [warn] [node-red-contrib-sm-ioplus/ioplus] Error: Cannot find module 'i2c-bus'
Require stack:
- /home/pi/ioplus-rpi/node-red-contrib-sm-ioplus/ioplus.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/local/lib/node_modules/node-red/lib/red.js
- /usr/local/lib/node_modules/node-red/red.js
11 Jun 15:33:30 - [warn] ------------------------------------------------------
11 Jun 15:33:30 - [info] Settings file  : /home/pi/.node-red/settings.js
11 Jun 15:33:30 - [info] Context store  : 'default' [module=memory]
11 Jun 15:33:30 - [info] User directory : /home/pi/.node-red
11 Jun 15:33:30 - [info] Projects directory: /home/pi/.node-red/projects
11 Jun 15:33:30 - [warn] No active project : using default flows file
11 Jun 15:33:30 - [info] Flows file     : /home/pi/.node-red/flows_homebridge.json
11 Jun 15:33:30 - [warn]`

i2c-bus is installed,

**Comment by alexburcea2877** [comment]
Hi, 
Looks like you forget to change directory before install the library, please follow the exact steps:
~$ cd ~/.node-red
~/.node-red$ npm install ~/ioplus-rpi/node-red-contrib-sm-ioplus

then restart the node-red and if is not working restart the RPI.

**Comment by hanyscz** [comment]
I try it all day today

`pi@homebridge:/var/lib/homebridge $ sudo nano /home/pi/.node-red/settings.js
pi@homebridge:/var/lib/homebridge $ cd ~/.node-red
pi@homebridge:~/.node-red $ npm install ~/ioplus-rpi/node-red-contrib-sm-ioplus

up to date, audited 91 packages in 2s`

`pi@homebridge:~/.node-red $ node-red-start

Start Node-RED
 
Once Node-RED has started, point a browser at http://192.168.88.162:1880
On Pi Node-RED works better with the Firefox or Chrome browser
 
Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot
 
To find more nodes and example flows - go to http://flows.nodered.org
 
Starting as a systemd service.
11 Jun 19:16:10 - [info]
Welcome to Node-RED
===================
11 Jun 19:16:10 - [info] Node-RED version: v1.3.5
11 Jun 19:16:10 - [info] Node.js  version: v14.16.1
11 Jun 19:16:10 - [info] Linux 5.10.17-v7l+ arm LE
11 Jun 19:16:11 - [info] Loading palette nodes
11 Jun 19:16:12 - [info] Dashboard version 2.29.1 started at /ui
11 Jun 19:16:13 - [warn] ------------------------------------------------------
11 Jun 19:16:13 - [warn] [node-red-contrib-sm-ioplus/ioplus] Error: Cannot find module 'i2c-bus'
Require stack:
- /home/pi/ioplus-rpi/node-red-contrib-sm-ioplus/ioplus.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/local/lib/node_modules/node-red/lib/red.js
- /usr/local/lib/node_modules/node-red/red.js
11 Jun 19:16:13 - [warn] ------------------------------------------------------
11 Jun 19:16:13 - [info] Settings file  : /home/pi/.node-red/settings.js
11 Jun 19:16:13 - [info] Context store  : 'default' [module=memory]
11 Jun 19:16:13 - [info] User directory : /home/pi/.node-red
11 Jun 19:16:13 - [warn] Projects disabled : editorTheme.projects.enabled=false
11 Jun 19:16:13 - [info] Flows file     : /home/pi/.node-red/flows_homebridge.json
11 Jun 19:16:13 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
11 Jun 19:16:13 - [info] Server now running at http://127.0.0.1:1880/
11 Jun 19:16:13 - [info] Starting flows
11 Jun 19:16:13 - [info] Started flows`

I have no idea what I'm doing wrong

node-red-contrib-i2c works fine with the library i2c-bus

**Comment by alexburcea2877** [comment]
I have no clever idea, let's try a stupid one:
~$ cd ~/.node-red
~/.node-red$ npm uninstall ~/ioplus-rpi/node-red-contrib-sm-ioplus

then reinstall the node

**Comment by hanyscz** [comment]
[node-red-contrib-sm-ioplus/ioplus] Error: Cannot find module 'i2c-bus'

**Comment by hanyscz** [comment]
I uninstalled and installed i2c-bus again.

Everything works :-)

we solved it all day ....

**Comment by alexburcea2877** [comment]
I am glad it woks.
Sorry you lost a day with this, never had this problem before but now we know.
