### ISSUE TITLE
Node Red issue with number of ADC inputs

### ISSUE THREAD

**Issue by flaguyme** [SequentMicrosystems/ioplus-rpi#7]
The node red distribution assumes a max limit of 4 ADC inputs.  The home automation card has 8.
The following files need to be modified to have the max number of channels moved from 4 to 8:  
 - ioplus-rpi/node-red-contrib-sm-ioplus/ioplus.html
-  ioplus-rpi/node-red-contrib-sm-ioplus/ioplus.js

**Comment by alexburcea2877** [comment]
Thank you for reporting the bug. We correct this and release the 1.0.2 version.

**Comment by alexburcea2877** [comment]
The problem was solved.
