### ISSUE TITLE
Node-Red Relay node not turning off

### ISSUE THREAD

**Issue by udilgp** [SequentMicrosystems/ioplus-rpi#8]
If the relay node's payload is set to anything other than msg.payload, the relay can only be turned on and cannot be turned off.
The payload mentioned is not the one received by the relay node but rather the one being sent out of the relay node.

**Comment by alexburcea2877** [comment]
Hi,
Sorry but I do not understand the problem. How suppose to work? It will be ok if we remove the useless option?

**Comment by alexburcea2877** [comment]
Hi, 
Hope you manage to solve the problem, I close this issue due inactivity.
